### ISSUE TITLE
Streams returned from the HttpClientRequestAdapter cannot be used

### ISSUE THREAD

**Issue by calebkiage** [microsoft/kiota-http-dotnet#10]
Streams returned from `HttpClientRequestAdapter` methods like `SendPrimitiveAsync<Stream>` cannot be used. The methods return disposed streams. I believe the culprit is the new `DrainAsync` method.

**Comment by andrueastman** [comment]
I believe there are scenarios where the response content may be large and consumers would not want/accept to load the entire stream into memory in some scenarios. On a side note, we should also probably add support for passing the [HttpCompletionOption ](https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpcompletionoption?view=net-6.0) to the httpClient as well.

I think adding a condition for streams should be okay as we already call `ReadAsStreamAsync()` here for streams so the connection should be released as we have read the response body.
 
https://github.com/microsoft/kiota-http-dotnet/blob/8de56f6f2ba7eaeca48831e04a574119888224a1/src/HttpClientRequestAdapter.cs#L158
