### ISSUE TITLE
System.Text.Json dependency constraint for .NET 8 scenarios

### ISSUE THREAD

**Issue by deepchoudhery** [microsoft/kiota-http-dotnet#166]
Hey, I use `Microsoft.Graph` package for the dotnet/Scaffolding project. For the new .NET 8 release of the scaffolding package, the dependency constraint this project has on System.Text.Json being [6.0, 8.0) is causing issues since it causes the default .NET 8 project's dependency on System.Text.Json to downgrade causing an error (dependency downgrade). Unless you have a workaround you can suggest.

**Comment by andrueastman** [comment]
Thanks for raising this @deepchoudhery 

We are planning to remove the constraint once .Net 8 is released anytime now. This is tracked via https://github.com/microsoft/kiota-serialization-json-dotnet/issues/105 for the serialization side. 

We'll keep this open to track the same for here.

**Comment by baywet** [comment]
Closing as duplicate, please subscribe to the issue Andrew linked to get updated.
