### ISSUE TITLE
How do I react to unexpected status codes?

### ISSUE THREAD

**Issue by KennethHoff** [microsoft/kiota-http-dotnet#171]
I originally posted this to the main https://github.com/microsoft/kiota repo, but I figured I should also ask here. Close whichever one you feel like doesn't make sense.

[Original post](https://github.com/microsoft/kiota/issues/3744)

**Comment by baywet** [comment]
Hi @kennethHoff,
Thanks for reaching out. Since this is a design question and an issue is already opened on the main repo, I'll go ahead and close this one here.
I'll provide an answer on the other one shortly.
