### ISSUE TITLE
ApiException should return mapped error response if it parses successfully

### ISSUE THREAD

**Issue by hwoodiwiss** [microsoft/kiota-http-dotnet#188]
##  Current Behavior

At the moment, when an HTTP request receives an error response, the response is parsed using a `ParsableFactory<IParsable>` that's passed in as a dictionary of HTTP Status Code -> Factory.

At the moment, when the error response is successfully parsed, it's used to set an activity tag for telemetry, then checked whether it's an exception or not.

https://github.com/microsoft/kiota-http-dotnet/blob/3c35d1c3c350c4b208e46b7c8bf8c93d518df916/src/HttpClientRequestAdapter.cs#L410-L423

## Desired Behavior

It would be useful for the parsed response to be bubbled up to the caller in the thrown `ApiException` so that this can be accessed in the calling code.

## API Changes

This would depend on an API change in `Microsoft.Kiota.Abstractions` in [`ApiException`](https://github.com/microsoft/kiota-abstractions-dotnet/blob/7085e020bd075d2fe8e3c23b975632084974caf4/src/ApiException.cs) to accommodate the error response value.

```diff
public class ApiException : Exception
{
    public ApiException() : base()
    public ApiException(string message) : base(message)
    public ApiException(string message, Exception innerException) : base(message, innerException)

    public int ResponseStatusCode { get; set; }
    public IDictionary<string, IEnumerable<string>> ResponseHeaders { get; set; }
+   public object? ResponseObject { get; set; }
}
```

**Comment by baywet** [comment]
Hi @hwoodiwiss,
Thanks for using kiota and for reaching out.
I'm not sure I follow what's being asked here: if the error response gets properly parsed, the thrown exception will actually be of that type. And will contain all the information that was described in the OpenAPI description for that status code.
Why would you need a "raw object" attached to it in addition?

**Comment by hwoodiwiss** [comment]
Ah. I completely missed that the error types are generated as inheritors of the `ApiException` type. 🤦🏼 
I'll close both of the related issues, sorry about that.
