### ISSUE TITLE
Package should be using a license expression

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-http-dotnet#229]
### Summary
I wish for the nuget packages to have the licence expression property set correctly

### Details

The licence expression property should be set to the correct licence type I.e. MIT as this will enable analysis of licences in use to occur in external tools & the license type will be shown in Nuget etc.

**Comment by andrueastman** [comment]
related to https://github.com/microsoft/kiota-abstractions-dotnet/issues/219

**Comment by baywet** [comment]
(let's use the issue in abstractions to discuss the nature of the changes and this issue to track the work here so we don't have a split conversation)
