### ISSUE TITLE
Leverage Framework dependencies rather than explicit where possible

### ISSUE THREAD

**Issue by thompson-tomo** [microsoft/kiota-http-dotnet#230]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Diagnostics.DiagnosticSource & System.Text.Json on net 6+. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by andrueastman** [comment]
Thanks for raising this @thompson-tomo.

Would you be willing to submit a PR similar to https://github.com/microsoft/kiota-serialization-json-dotnet/pull/209 for this?

**Comment by thompson-tomo** [comment]
@andrueastman sure I will go through submitting PR's in the coming days.
