### ISSUE TITLE
Kiota HttpAdapter does not support Http/2

### ISSUE THREAD

**Issue by dev-tony-hu** [microsoft/kiota-http-dotnet#231]
Currently Http/2 is used widely, like Microsoft Graph support Http/2 in Sep 2023.
In previously Microsoft Graph core SDK it will use Http/2 by default, but since 5.x which use Kiota to send http request, it only support Http1.1, and can't change it.
Should use http 2.0 by default, and it can fall back to Http 1.1 if server side does not support it.

Reference:
MC447341 – Beginning September 15, 2023, the Microsoft Graph service (graph.microsoft.com) will enable HTTP version 2 (HTTP/2) in addition to HTTP/1.1. for API requests. 

https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/issues/357

**Comment by andrueastman** [comment]
Closed via https://github.com/microsoft/kiota-http-dotnet/pull/232
