### ISSUE TITLE
Defaulting to HTTP/2.0 breaks consumers using .NET Framework

### ISSUE THREAD

**Issue by BodrickLight** [microsoft/kiota-http-dotnet#237]
#231 introduces a breaking change for consumers that use .NET Framework, as HTTP/2.0 is not a supported version in `HttpRequestMessage`.

Minimal repro with `<TargetFramework>net472</TargetFramework>`:

```csharp
var adapter = new HttpClientRequestAdapter(new AnonymousAuthenticationProvider());
await adapter.SendNoContentAsync(new RequestInformation()
{
    URI = new Uri("http://example.com")
});
```

This works as expected on `Microsoft.Kiota.Http.HttpClientLibrary` version `1.3.8`, but throws the following exception on `1.3.9` and `1.3.10`:

```
Unhandled Exception: System.ArgumentException: Only HTTP/1.0 and HTTP/1.1 version requests are currently supported.
Parameter name: value
   at System.Net.HttpWebRequest.set_ProtocolVersion(Version value)
   at System.Net.Http.HttpClientHandler.CreateAndPrepareWebRequest(HttpRequestMessage request)
   at System.Net.Http.HttpClientHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
```

**Comment by jcsawyer** [comment]
I missed the PR but when the target is `net462`, the package `System.Net.Http.WinHttpHandler` is referenced.
If the target of the consumer is `net472`, surely this package will not be pulled in and `WinHttpHandler` will not be available?

**Comment by baywet** [comment]
@jcsawyer this directive `#if NETFRAMEWORK` covers all net framework versions (anything not net core effectively), so I'm not sure what the concern is?

**Comment by jcsawyer** [comment]
@baywet if the package `System.Net.Http.WinHttpHandler` is referenced when the target is `net462`, will this work for consumers with a target of `net472` or will it result in a `The type or namespace name 'WinHttpHandler' could not be found`?

I'm suspecting the latter?

The `#if NETFRAMEWORK` will resolve the type for `net462` but no other `NETFRAMEWORK` target?

**Comment by baywet** [comment]
Ah, you're referring to [this](https://github.com/microsoft/kiota-http-dotnet/pull/238/files#diff-8c992ac489d1ed02a39552851b1e1c07f4b66548702eb52d5bdecdd1ac8c14c0R55)

I'm not sure whether other versions of netfx will favour the net462 version or the net standard versions. Maybe this is something that @andrueastman can shed a light on?
We might have to update the directive, or the condition for the package.

**Comment by jcsawyer** [comment]
I am indeed.
If I drop:
```
<ItemGroup Condition="'$(TargetFramework)' == 'net462'">
    <PackageReference Include="System.Net.Http.WinHttpHandler" Version="[6.0,9.0)" />
</ItemGroup>
```
in a `net472` project, any references to `WinHttpHandler` will fail to build.

**Comment by baywet** [comment]
Thanks for the additional information.
This is a fix we had [in the previous version of the microsoft graph sdk for years](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/98f853c180c5c312afb0ec8548acbe36b408d9f2/src/Microsoft.Graph.Core/Requests/GraphClientFactory.cs#L235) nad [here](https://github.com/microsoftgraph/msgraph-sdk-dotnet-core/blob/98f853c180c5c312afb0ec8548acbe36b408d9f2/src/Microsoft.Graph.Core/Microsoft.Graph.Core.csproj#L75) which only [had net462 and netstandard2 targets](https://www.nuget.org/packages/Microsoft.Graph.Core/2.0.15#supportedframeworks-body-tab) while [net472 was already available for years](https://devblogs.microsoft.com/dotnet/announcing-the-net-framework-4-7-2) and we didn't get complaints about missing dependencies?

**Comment by andrueastman** [comment]
I believe in the context of a `net472` project the package manager will pull the `net462` dll and resolve the dependency. 
This is validated with the latest https://www.nuget.org/packages/Microsoft.Kiota.Http.HttpClientLibrary/1.3.11 release. 
The sample[ net4.7.2 project](https://github.com/andrueastman/TestClient/blob/d22ff477887087f5f68daed43c6c9858d0e08149/TestClient/TestClient.csproj#L11) builds and runs as expected.

Any chance you can confirm if you are referencing the project as a submodule or as a package?

**Comment by jcsawyer** [comment]
TIL NET Framework packages are confusing as anything! 
It looks like everything is working with the `1.3.11` package - running a full e2e pipeline through on component to fully confirm for specific case, but I can re-open/open new issue if there are any problems there.

Many thanks

**Comment by baywet** [comment]
Thanks for keeping us in check! Closing
