### ISSUE TITLE
SocketsHttpHandler as final handler

### ISSUE THREAD

**Issue by ghelyar** [microsoft/kiota-http-dotnet#239]
I noticed in #237 the default handler on .NET Framework was changed to `WinHttpHandler`.

Should the default on .NET (Core) be [SocketsHttpHandler](https://learn.microsoft.com/en-us/dotnet/api/system.net.http.socketshttphandler?view=net-8.0) rather than `HttpClientHandler`?

It was changed to the default handler in .NET Core 2.1 and the docs say
> A significant performance improvement when compared with the previous implementation.

**Comment by ghelyar** [comment]
Actually never mind it looks like HttpClientHandler uses SocketsHttpHandler now anyway

https://github.com/dotnet/runtime/blob/main/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs

**Comment by andrueastman** [comment]
Thanks for raising this @ghelyar 

As you pointed out the `SocketsHttpHandler` is already the default handler type for any non-browser environments and `WinHttpHandler` is only used in netfx to unlock Http/2 scenarios in the environment. 

https://github.com/dotnet/runtime/blob/2a176695d2c0a6f7199a61e2cfc307eeecef4790/src/libraries/System.Net.Http/src/System/Net/Http/HttpClientHandler.cs#L18

Any chance you can confirm if this issue is still relevant?

**Comment by ghelyar** [comment]
Is there any reason to continue to use `HttpClientHandler` over `SocketsHttpHandler` on targets where `SocketsHttpHandler` is available?

using `SocketsHttpHandler` (and `WinHttpHandler`) directly would also allow `EnableMultipleHttp2Connections` to be used for performance on .NET 5+, if that's helpful. [It's recommended for gRPC](https://learn.microsoft.com/en-us/aspnet/core/grpc/performance?view=aspnetcore-8.0#connection-concurrency), for example, and the same logic could apply to all HTTP/2 connections where you may have a lot of concurrent requests going to the same service on the same multiplexed connection, which could apply with things like microservices.

More info here: https://devblogs.microsoft.com/dotnet/net-5-new-networking-improvements/#multiple-connections-with-http-2

Right now this is just a suggestion that could improve performance. I don't know if the change to HTTP/2 is actually going to cause performance issues without this or not yet.

**Comment by andrueastman** [comment]
To confirm here, what you are saying here is that 

- targets of `NET Core 2.1-3.1` will use `HttpClientHandler` and not internally use the `SocketsHttpHandler` so we should explicitly define `SocketsHttpHandler` as the final handler
- for better perf of HTTP/2 we should set the `EnableMultipleHttp2Connections` property on creating the handler (SocketsHttpHandler or WinHttpHandler) where we can by default.

Yes?

**Comment by ghelyar** [comment]
Yes

The other target frameworks would be e.g. netstandard2.0 where `SocketsHttpHandler` is not available but e.g. .net framework would no longer use the .net standard target anyway because if any compatible .net framework target exists then a .net framework consumer will use it over any .net standard target, so not much would still use netstandard2.0; maybe some Xamarin consumers or something like that.

**Comment by andrueastman** [comment]
Thanks for clarifying @ghelyar 

Any chance you'd be willing to submit a PR for this?

**Comment by ghelyar** [comment]
Yes I can submit a PR for this when I get some time
