### ISSUE TITLE
Hard dependency on MS.Kiota.Abstractions 1.8.3 causes runtime load errors.

### ISSUE THREAD

**Issue by johnholliday** [microsoft/kiota-http-dotnet#256]
There is a hard dependency on Microsoft.Kiota.Abstractions version 1.8.3, which is a lower version than the core suite of required assemblies (for example Microsoft.Kiota.Serialization.Json).  This results in runtime errors that requires manual distribution of the 1.8.3 assembly alongside the 1.8.4+ versions recommended by the Kiota tooling.

![image](https://github.com/microsoft/kiota-http-dotnet/assets/5294044/d23a9132-fb2d-429c-ac1e-97395e192d10)

![image](https://github.com/microsoft/kiota-http-dotnet/assets/5294044/d8d54d48-b3da-438c-8c48-beea310de925)

**Comment by baywet** [comment]
Hi @johnholliday 
Thanks for letting us know.
Authored #257 to address this.
