### ISSUE TITLE
Module dependencies cause runtime exceptions.

### ISSUE THREAD

**Issue by johnholliday** [microsoft/kiota-http-dotnet#258]
Thanks for the quick fix attempt.  Unfortunately the real issue appears to be that there is no consistency in the dependencies between the various Kiota modules, which should all be aligned.  It is currently not possible to find a working combination of required modules that do not fail at runtime.

> NOTE: I am building a class library that uses a relatively simple (at the moment) API.  Happy to entertain a reliable work-around if one exists.

**Fail: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.8.3.0...**

> NOTE: Cannot link to version 1.8.3 because of required dependencies on 1.8.4

```
Serialization.Text (1.1.5) => Abstractions >= 1.8.4
Serialization.Multipart (1.1.4) => Abstractions >= 1.8.4
Serialization.Json (1.2.3) => Abstractions >= 1.8.4
Serialization.Form (1.1.6) => Abstractions >= 1.8.4
Http.HttpClientLibrary (1.4.1) => Abstractions >= 1.8.3
Authentication.Azure (1.1.5) => Abstractions >= 1.8.3
```
---
**Fail: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.7.11.0...**

> NOTE: Cannot link to version 1.7.11 because of required dependencies on 1.8.3.

```
Serialization.Text (1.1.4) => Abstractions >= 1.7.11
Serialization.Multipart (1.1.3) => Abstractions >= 1.7.10
Serialization.Json (1.2.1) => Abstractions >= 1.8.3
Serialization.Form (1.1.5) => Abstractions >= 1.7.11
Http.HttpClientLibrary (1.4.0) => Abstractions >= 1.8.3
Authentication.Azure (1.1.5) => Abstractions >= 1.8.3
```
---
**Fail: Could not load file or assembly 'Microsoft.Kiota.Abstractions, Version=1.9.0.0...**

> NOTE: Cannot link to version 1.9.0 because of required dependency on 1.9.1
```
Serialization.Text (1.2.0) => Abstractions >= 1.9.0
Serialization.Multipart (1.1.4) => Abstractions >= 1.8.4
Serialization.Json (1.3.0) => Abstractions >= 1.9.0
Serialization.Form (1.2.0) => Abstractions >= 1.9.0
Http.HttpClientLibrary (1.4.2) => Abstractions >= 1.9.1 < 2.0.0
Authentication.Azure (1.1.5) => Abstractions >= 1.8.3
```

_Originally posted by @johnholliday in https://github.com/microsoft/kiota-http-dotnet/issues/257#issuecomment-2124056504_

**Comment by baywet** [comment]
Thanks for the additional information.
Can you update (from the last one you've shared):

Form to 1.2.2
Json to 1.3.1
And share the results?
I believe that multipart and authentication azure probably need a patch bump and release.

**Comment by johnholliday** [comment]
Fails at runtime.  Cannot find Microsoft.Kiota.Abstractions, Version=1.9.0.0 (because of Microsoft.Kiota.Serialization.Text dependency on 1.9.0.0)

**Comment by baywet** [comment]
@andrueastman can you go update all the other dependencies to a range requirement on abstractions instead whenever you get a couple of minutes please?

**Comment by johnholliday** [comment]
Any updates?

**Comment by baywet** [comment]
(Andrew is located in Kenya, we probably won't get an answer before tomorrow)

**Comment by andrueastman** [comment]
> @andrueastman can you go update all the other dependencies to a range requirement on abstractions instead whenever you get a couple of minutes please?

Will send a PRs to resolve these in a bit.

**Comment by baywet** [comment]
@johnholliday all dependencies have been published so they are aligned. Pulling the latest of everything should solve the issue you're facing. Let us know!
