### ISSUE TITLE
GraphServiceClient error with Kiota version 1.4.2+

### ISSUE THREAD

**Issue by derekreynolds882** [microsoft/kiota-http-dotnet#261]
Starting with version 1.4.2 of Microsoft.Kiota.Http.HttpClientLibrary ,  there is a runtime error for the GraphServiceClient constructor.

_System.MissingMethodException: 'Method not found: 'System.Collections.Generic.IList`1<System.Net.Http.DelegatingHandler> Microsoft.Kiota.Http.HttpClientLibrary.KiotaClientFactory.CreateDefaultHandlers()'.'_

Is there a workaround or fix for this?

**Comment by DarthSonic** [comment]
Same issue for us.

```
var authenticationProvider = new BaseBearerTokenAuthenticationProvider(tokenProvider);
var msGraphClient = new GraphServiceClient(authenticationProvider);
```

expection is throwing on new GraphServiceClient.

**Comment by andrueastman** [comment]
Thanks for raising this @derekreynolds882 

As this seems to be related to the graph SDK, we'll close this one for now and track this over at https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/2520

**Comment by DarthSonic** [comment]
Solution is to use at least v 3.1.12 of Microsoft.Graph.Core package.
