### ISSUE TITLE
Dependency on Microsoft.Kiota.Abstractions >= v1.9.1 causes issues

### ISSUE THREAD

**Issue by kfcampbell** [microsoft/kiota-http-dotnet#264]
Hi! I think this is a similar issue to #256. In [src/Microsoft.Kiota.Http.HttpClientLibrary.csproj](https://github.com/microsoft/kiota-http-dotnet/blob/6c1e799f63a26b9209e7153d7f1eb2d2c730e9f6/src/Microsoft.Kiota.Http.HttpClientLibrary.csproj#L47-L50), there's a dependency on Microsoft.Kiota.Abstractions `Version="[1.9.1, 2.0.0)"`. 

However, when running the Kiota CLI (v1.15.0) `kiota info -l CSharp --json`, the dependency given is 

```
{
      "name": "Microsoft.Kiota.Abstractions",
      "version": "1.9.0"
},
```

Since our project treats warnings as errors, this breaks us at build, but otherwise would break at runtime I believe. Example output of building a .csproj that installs recommended packages based upon that `kiota info` output:

```
/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/src/GitHub.Octokit.SDK.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.Kiota.Abstractions from 1.9.1 to 1.9.0. Reference the package directly from the project to select a different version.  [/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/GitHub.Octokit.sln]
/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/src/GitHub.Octokit.SDK.csproj : error NU1605:  GitHub.Octokit.SDK -> Microsoft.Kiota.Http.HttpClientLibrary 1.4.3 -> Microsoft.Kiota.Abstractions (>= 1.9.1 && < 2.0.0)  [/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/GitHub.Octokit.sln]
/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/src/GitHub.Octokit.SDK.csproj : error NU1605:  GitHub.Octokit.SDK -> Microsoft.Kiota.Abstractions (>= 1.9.0) [/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/GitHub.Octokit.sln]
/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/test/Tests.csproj : error NU1605: Warning As Error: Detected package downgrade: Microsoft.Kiota.Abstractions from 1.9.1 to 1.9.0. Reference the package directly from the project to select a different version.  [/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/GitHub.Octokit.sln]
/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/test/Tests.csproj : error NU1605:  Tests -> GitHub.Octokit.SDK -> Microsoft.Kiota.Http.HttpClientLibrary 1.4.3 -> Microsoft.Kiota.Abstractions (>= 1.9.1 && < 2.0.0)  [/home/kfcampbell/github/dev/source-generator/stage/dotnet-sdk/GitHub.Octokit.sln]
```

Please let me know if you'd like more information!

**Comment by andrueastman** [comment]
Thanks for raising this @kfcampbell 

For now, I would suggest updating abstractions to the latest version to resolve this (v1.9.6) as the Kiota info command in 1.5.0 is showing 1.9.0 due a misaligned configuration (see https://github.com/microsoft/kiota/issues/4825). We've since resolved this, and future versions should show the correct version.

Please try this out and let us know if this is helpful!

**Comment by kfcampbell** [comment]
Unfortunately this isn't easily done, as our tooling treats the `kiota info` command as a source of truth and parses the results of that command to install dependencies. Right now as a workaround we're pinning to Kiota v1.14.0.

**Comment by baywet** [comment]
Thanks for the additional information. If you use the last preview version it should solve your issue.
Also, since this has "already been solved" and only needs to be released on a mainline release, we're unlikely to make any additional change at this point.

**Comment by kfcampbell** [comment]
Okay! It sounds like the best course of action for us then is to stay pinned on v1.14.0 for now, skip v1.15.0, and go straight to v1.16.0 when it releases next month.

**Comment by baywet** [comment]
I'm going to go ahead and close this issue since there's no further action on kiota's side. Let us know if you need anything else!
