### ISSUE TITLE
Rename ThrowFailedResponse to ThrowIfFailedResponse

### ISSUE THREAD

**Issue by darrelmiller** [microsoft/kiota-http-dotnet#55]
This method name confused me. How do folks feel like about renaming it to ThrowIfFailedResponse?

https://github.com/microsoft/kiota-http-dotnet/blob/20633e28e6178fc0aa6bbe86fbd20c1ea30933f8/src/HttpClientRequestAdapter.cs#L88-L94

**Comment by baywet** [comment]
Makes sense, plus it's private so it won't be a breaking change.
@andruestman would you mind doing Java/Go/TypeScript on top of dotnet please?
